### ISSUE TITLE
AsmProfiler does not work with Delphi 11.2

### ISSUE THREAD

**Issue by jBitHub** [andremussche/asmprofiler#5]
AsmProfiler does not work with Delphi 11.2. An Access Violation occurs immediately when starting the profiling.

**Comment by dcabale** [comment]
I also would like to try that project with Delphi 12.x
@andremussche Andre, is that project dead?

**Comment by andremussche** [comment]
I will ask my boss for a copy of D12, did the AV occur in 32bit mode?

**Comment by dcabale** [comment]
> I will ask my boss for a copy of D12, did the AV occur in 32bit mode?

I believe your question is directed to @jBitHub, as I did not even install the asmProfiler

**Comment by jBitHub** [comment]
> ..., did the AV occur in 32bit mode?

Yes, the access violation occurred under 32bit. I realise that the AsmProfiler does not run under 64bit. There are many wrong castings of pointers in the code. Instead of NativeUInt(Pointer) Integer(Pointer) is used.
I have already compiled the project (AsmProfiler.dll) under 11.3. I have used the latest code of all 3rd party components. Then applications can be started with the AsmProfiler.dll. Measuring any methods is impossible. Reading the map file no longer works properly. Perhaps the structure of the map file has changed.

**Comment by andremussche** [comment]
@jBitHub and @dcabale I found the problem: you **must** disable "Support addresss space layout randomization (ASLR)", otherwise the offsets to the functions in the memory (according to the map file) cannot be used anymore (because the applications is loaded at a random location). And probably "data execution prevention compatible" should be disabled too (because of assembly detouring technique). After disabling both options my "DllTestApp" was working again.

![image](https://github.com/andremussche/asmprofiler/assets/3033230/3b32c49d-8023-4129-9982-2819dd47fe88)
